name: Node.js CI/CD

on:
  release:
    types: [created]
  push:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build -t geprekmumbul/snipe-it .
      - name: Login to Dockerhub
        run: docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
      - name: Publish Docker Image to Dockerhub
        run: docker push geprekmumbul/snipe-it:latest

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
          
  deploy:
    needs: [build, tests]
    runs-on: self-hosted
    steps:
      - name: Pull image dockerhub
        run: docker pull geprekmumbul/snipe-it:latest
      - name: Delete old container
        run: docker rm -f snipeit
      - name: run docker container
        run: docker run -d -p 9000:9000 --name snipeit geprekmumbul/snipe-it
        
